# Generated by Django 4.2.24 on 2025-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0002_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9999),
        ),
    ]
